version: "3"
services:
  joint_scheduler:
    build: .
    restart: always
    ports:
      - "8001:80"
    volumes:
    - /mnt/stock_data/summergreen/data/tick_day_parquet:/data/tick_day_parquet
    - /mnt/stock_data/summergreen/log:/log
    environment:
      TZ: "Asia/Shanghai"
    depends_on:
      - "redis"
      - "redis_k"
  redis:
    image: redis:6.0.8-alpine
    restart: always
    ports:
      - 8011:6379
    environment:
      TZ: "Asia/Shanghai"
  redis_k:
    image: redis:6.0.8-alpine
    restart: always
    ports:
      - 8012:6379
    environment:
      TZ: "Asia/Shanghai"