tick_redis_config:
  db: 2
  decode_responses: 1
  host: localhost
  port: 6379

mirror_redis_config:
  db: 3
  decode_responses: 0
  host: localhost
  port: 6379

to_day_parquet_dir: /mnt/stock_data/stock_tick_current_day/