ask1:
  rename: a1_p
  type: float
ask1_volume:
  rename: a1_v
  type: float
ask2:
  rename: a2_p
  type: float
ask2_volume:
  rename: a2_v
  type: float
ask3:
  rename: a3_p
  type: float
ask3_volume:
  rename: a3_v
  type: float
ask4:
  rename: a4_p
  type: float
ask4_volume:
  rename: a4_v
  type: float
ask5:
  rename: a5_p
  type: float
ask5_volume:
  rename: a5_v
  type: float
bid1:
  rename: b1_p
  type: float
bid1_volume:
  rename: b1_v
  type: float
bid2:
  rename: b2_p
  type: float
bid2_volume:
  rename: b2_v
  type: float
bid3:
  rename: b3_p
  type: float
bid3_volume:
  rename: b3_v
  type: float
bid4:
  rename: b4_p
  type: float
bid4_volume:
  rename: b4_v
  type: float
bid5:
  rename: b5_p
  type: float
bid5_volume:
  rename: b5_v
  type: float
buy:
  rename: buy
  type: float
close:
  rename: ~
  type: float
curr_time_str:
  rename: curr_time_str
  type: str
date:
  rename: date
  type: str
high:
  rename: high
  type: float
low:
  rename: low
  type: float
name:
  rename: ~
  type: str
now:
  rename: current
  type: float
open:
  rename: ~
  type: float
sell:
  rename: sell
  type: float
time:
  rename: time
  type: str
turnover:
  rename: volume
  type: float
volume:
  rename: money
  type: float
