bar_numpy_datatype:
  code: U10
  current: f8
  high: f8
  low: f8
  money: f8
  time: f8
  volume: i8
pandas_datatype:
  a1_p: float16
  a1_v: int64
  a2_p: float16
  a2_v: int64
  a3_p: float16
  a3_v: int64
  a4_p: float16
  a4_v: int64
  a5_p: float16
  a5_v: int64
  b1_p: float16
  b1_v: int64
  b2_p: float16
  b2_v: int64
  b3_p: float16
  b3_v: int64
  b4_p: float16
  b4_v: int64
  b5_p: float16
  b5_v: int64
  code: object
  current: float16
  high: float16
  low: float16
  money: float16
  time: datetime64
  volume: int64
tick_numpy_datatype:
  a1_p: f8
  a1_v: i8
  a2_p: f8
  a2_v: i8
  a3_p: f8
  a3_v: i8
  a4_p: f8
  a4_v: i8
  a5_p: f8
  a5_v: i8
  b1_p: f8
  b1_v: i8
  b2_p: f8
  b2_v: i8
  b3_p: f8
  b3_v: i8
  b4_p: f8
  b4_v: i8
  b5_p: f8
  b5_v: i8
  code: U10
  current: f8
  high: f8
  low: f8
  money: f8
  money_incr: f8
  time: f8
  volume: i8
  volume_incr: i8
