bar_dtypes:
  code: string
  current: float64
  high: float64
  low: float64
  money: float64
  time: datetime64
  volume: int64
tick_dtypes:
  code: string
  time: datetime64
  current: float64
  high: float64
  low: float64
  volume: int64
  money: float64
  b1_v: int64
  b1_p: float64
  b2_v: int64
  b2_p: float64
  b3_v: int64
  b3_p: float64
  b4_v: int64
  b4_p: float64
  b5_v: int64
  b5_p: float64
  a1_v: int64
  a1_p: float64
  a2_v: int64
  a2_p: float64
  a3_v: int64
  a3_p: float64
  a4_v: int64
  a4_p: float64
  a5_v: int64
  a5_p: float64

tick_increased_dtypes:
  volume_increased: int64
  money_increased: float64
