bar_dtypes:
  code: O
  time: M
  open: f8
  close: f8
  high: f8
  low: f8
  volume: i8
  money: f8
tick_dtypes:
  code: O
  time: M
  current: f8
  high: f8
  low: f8
  volume: i8
  money: f8
  b1_v: i8
  b1_p: f8
  b2_v: i8
  b2_p: f8
  b3_v: i8
  b3_p: f8
  b4_v: i8
  b4_p: f8
  b5_v: i8
  b5_p: f8
  a1_v: i8
  a1_p: f8
  a2_v: i8
  a2_p: f8
  a3_v: i8
  a3_p: f8
  a4_v: i8
  a4_p: f8
  a5_v: i8
  a5_p: f8
tick_increased_dtypes:
  volume_increased: i8
  money_increased: f8
